#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Rutas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rutas")]
	public partial class RutaBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAsignacion_Ruta(Asignacion_Ruta instance);
    partial void UpdateAsignacion_Ruta(Asignacion_Ruta instance);
    partial void DeleteAsignacion_Ruta(Asignacion_Ruta instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertDetalle_Factura(Detalle_Factura instance);
    partial void UpdateDetalle_Factura(Detalle_Factura instance);
    partial void DeleteDetalle_Factura(Detalle_Factura instance);
    partial void InsertDetalle_Pedido(Detalle_Pedido instance);
    partial void UpdateDetalle_Pedido(Detalle_Pedido instance);
    partial void DeleteDetalle_Pedido(Detalle_Pedido instance);
    partial void InsertDevolucion(Devolucion instance);
    partial void UpdateDevolucion(Devolucion instance);
    partial void DeleteDevolucion(Devolucion instance);
    partial void InsertEntrega(Entrega instance);
    partial void UpdateEntrega(Entrega instance);
    partial void DeleteEntrega(Entrega instance);
    partial void InsertFactura(Factura instance);
    partial void UpdateFactura(Factura instance);
    partial void DeleteFactura(Factura instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertPunto(Punto instance);
    partial void UpdatePunto(Punto instance);
    partial void DeletePunto(Punto instance);
    partial void InsertRuta(Ruta instance);
    partial void UpdateRuta(Ruta instance);
    partial void DeleteRuta(Ruta instance);
    #endregion
		
		public RutaBDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RutasConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RutaBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RutaBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RutaBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RutaBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asignacion_Ruta> Asignacion_Ruta
		{
			get
			{
				return this.GetTable<Asignacion_Ruta>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Auditoria> Auditoria
		{
			get
			{
				return this.GetTable<Auditoria>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Factura> Detalle_Factura
		{
			get
			{
				return this.GetTable<Detalle_Factura>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Pedido> Detalle_Pedido
		{
			get
			{
				return this.GetTable<Detalle_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Devolucion> Devolucion
		{
			get
			{
				return this.GetTable<Devolucion>();
			}
		}
		
		public System.Data.Linq.Table<Entrega> Entrega
		{
			get
			{
				return this.GetTable<Entrega>();
			}
		}
		
		public System.Data.Linq.Table<Factura> Factura
		{
			get
			{
				return this.GetTable<Factura>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedido
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Punto> Punto
		{
			get
			{
				return this.GetTable<Punto>();
			}
		}
		
		public System.Data.Linq.Table<Ruta> Ruta
		{
			get
			{
				return this.GetTable<Ruta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asignacion_Ruta")]
	public partial class Asignacion_Ruta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_asignacion;
		
		private int _id_ruta;
		
		private int _id_usuario;
		
		private System.DateTime _fecha_asignacion;
		
		private System.TimeSpan _hora_asignacion;
		
		private int _estado_asignacion;
		
		private EntitySet<Devolucion> _Devolucion;
		
		private EntitySet<Entrega> _Entrega;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Ruta> _Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_asignacionChanging(int value);
    partial void Onid_asignacionChanged();
    partial void Onid_rutaChanging(int value);
    partial void Onid_rutaChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onfecha_asignacionChanging(System.DateTime value);
    partial void Onfecha_asignacionChanged();
    partial void Onhora_asignacionChanging(System.TimeSpan value);
    partial void Onhora_asignacionChanged();
    partial void Onestado_asignacionChanging(int value);
    partial void Onestado_asignacionChanged();
    #endregion
		
		public Asignacion_Ruta()
		{
			this._Devolucion = new EntitySet<Devolucion>(new Action<Devolucion>(this.attach_Devolucion), new Action<Devolucion>(this.detach_Devolucion));
			this._Entrega = new EntitySet<Entrega>(new Action<Entrega>(this.attach_Entrega), new Action<Entrega>(this.detach_Entrega));
			this._Usuario = default(EntityRef<Usuario>);
			this._Ruta = default(EntityRef<Ruta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_asignacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_asignacion
		{
			get
			{
				return this._id_asignacion;
			}
			set
			{
				if ((this._id_asignacion != value))
				{
					this.Onid_asignacionChanging(value);
					this.SendPropertyChanging();
					this._id_asignacion = value;
					this.SendPropertyChanged("id_asignacion");
					this.Onid_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ruta", DbType="Int NOT NULL")]
		public int id_ruta
		{
			get
			{
				return this._id_ruta;
			}
			set
			{
				if ((this._id_ruta != value))
				{
					if (this._Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rutaChanging(value);
					this.SendPropertyChanging();
					this._id_ruta = value;
					this.SendPropertyChanged("id_ruta");
					this.Onid_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_asignacion", DbType="Date NOT NULL")]
		public System.DateTime fecha_asignacion
		{
			get
			{
				return this._fecha_asignacion;
			}
			set
			{
				if ((this._fecha_asignacion != value))
				{
					this.Onfecha_asignacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_asignacion = value;
					this.SendPropertyChanged("fecha_asignacion");
					this.Onfecha_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_asignacion", DbType="Time NOT NULL")]
		public System.TimeSpan hora_asignacion
		{
			get
			{
				return this._hora_asignacion;
			}
			set
			{
				if ((this._hora_asignacion != value))
				{
					this.Onhora_asignacionChanging(value);
					this.SendPropertyChanging();
					this._hora_asignacion = value;
					this.SendPropertyChanged("hora_asignacion");
					this.Onhora_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_asignacion", DbType="Int NOT NULL")]
		public int estado_asignacion
		{
			get
			{
				return this._estado_asignacion;
			}
			set
			{
				if ((this._estado_asignacion != value))
				{
					this.Onestado_asignacionChanging(value);
					this.SendPropertyChanging();
					this._estado_asignacion = value;
					this.SendPropertyChanged("estado_asignacion");
					this.Onestado_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asignacion_Ruta_Devolucion", Storage="_Devolucion", ThisKey="id_asignacion", OtherKey="id_asignacion")]
		public EntitySet<Devolucion> Devolucion
		{
			get
			{
				return this._Devolucion;
			}
			set
			{
				this._Devolucion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asignacion_Ruta_Entrega", Storage="_Entrega", ThisKey="id_asignacion", OtherKey="id_asignacion")]
		public EntitySet<Entrega> Entrega
		{
			get
			{
				return this._Entrega;
			}
			set
			{
				this._Entrega.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Asignacion_Ruta", Storage="_Usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Asignacion_Ruta.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Asignacion_Ruta.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Asignacion_Ruta", Storage="_Ruta", ThisKey="id_ruta", OtherKey="id_ruta", IsForeignKey=true)]
		public Ruta Ruta
		{
			get
			{
				return this._Ruta.Entity;
			}
			set
			{
				Ruta previousValue = this._Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ruta.Entity = null;
						previousValue.Asignacion_Ruta.Remove(this);
					}
					this._Ruta.Entity = value;
					if ((value != null))
					{
						value.Asignacion_Ruta.Add(this);
						this._id_ruta = value.id_ruta;
					}
					else
					{
						this._id_ruta = default(int);
					}
					this.SendPropertyChanged("Ruta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Devolucion(Devolucion entity)
		{
			this.SendPropertyChanging();
			entity.Asignacion_Ruta = this;
		}
		
		private void detach_Devolucion(Devolucion entity)
		{
			this.SendPropertyChanging();
			entity.Asignacion_Ruta = null;
		}
		
		private void attach_Entrega(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Asignacion_Ruta = this;
		}
		
		private void detach_Entrega(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Asignacion_Ruta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _usuario_;
		
		private string _nombre_usuario;
		
		private string _telefono_usuario;
		
		private string _correo_usuario;
		
		private string _contraseña_usuario;
		
		private string _puesto_usuario;
		
		private decimal _estado_usuario;
		
		private EntitySet<Asignacion_Ruta> _Asignacion_Ruta;
		
		private EntitySet<Factura> _Factura;
		
		private EntitySet<Pedido> _Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onusuario_Changing(string value);
    partial void Onusuario_Changed();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void Ontelefono_usuarioChanging(string value);
    partial void Ontelefono_usuarioChanged();
    partial void Oncorreo_usuarioChanging(string value);
    partial void Oncorreo_usuarioChanged();
    partial void Oncontraseña_usuarioChanging(string value);
    partial void Oncontraseña_usuarioChanged();
    partial void Onpuesto_usuarioChanging(string value);
    partial void Onpuesto_usuarioChanged();
    partial void Onestado_usuarioChanging(decimal value);
    partial void Onestado_usuarioChanged();
    #endregion
		
		public Usuario()
		{
			this._Asignacion_Ruta = new EntitySet<Asignacion_Ruta>(new Action<Asignacion_Ruta>(this.attach_Asignacion_Ruta), new Action<Asignacion_Ruta>(this.detach_Asignacion_Ruta));
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario_
		{
			get
			{
				return this._usuario_;
			}
			set
			{
				if ((this._usuario_ != value))
				{
					this.Onusuario_Changing(value);
					this.SendPropertyChanging();
					this._usuario_ = value;
					this.SendPropertyChanged("usuario_");
					this.Onusuario_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_usuario", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string telefono_usuario
		{
			get
			{
				return this._telefono_usuario;
			}
			set
			{
				if ((this._telefono_usuario != value))
				{
					this.Ontelefono_usuarioChanging(value);
					this.SendPropertyChanging();
					this._telefono_usuario = value;
					this.SendPropertyChanged("telefono_usuario");
					this.Ontelefono_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correo_usuario
		{
			get
			{
				return this._correo_usuario;
			}
			set
			{
				if ((this._correo_usuario != value))
				{
					this.Oncorreo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._correo_usuario = value;
					this.SendPropertyChanged("correo_usuario");
					this.Oncorreo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña_usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string contraseña_usuario
		{
			get
			{
				return this._contraseña_usuario;
			}
			set
			{
				if ((this._contraseña_usuario != value))
				{
					this.Oncontraseña_usuarioChanging(value);
					this.SendPropertyChanging();
					this._contraseña_usuario = value;
					this.SendPropertyChanged("contraseña_usuario");
					this.Oncontraseña_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puesto_usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string puesto_usuario
		{
			get
			{
				return this._puesto_usuario;
			}
			set
			{
				if ((this._puesto_usuario != value))
				{
					this.Onpuesto_usuarioChanging(value);
					this.SendPropertyChanging();
					this._puesto_usuario = value;
					this.SendPropertyChanged("puesto_usuario");
					this.Onpuesto_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_usuario", DbType="Decimal(1,0) NOT NULL")]
		public decimal estado_usuario
		{
			get
			{
				return this._estado_usuario;
			}
			set
			{
				if ((this._estado_usuario != value))
				{
					this.Onestado_usuarioChanging(value);
					this.SendPropertyChanging();
					this._estado_usuario = value;
					this.SendPropertyChanged("estado_usuario");
					this.Onestado_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Asignacion_Ruta", Storage="_Asignacion_Ruta", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<Asignacion_Ruta> Asignacion_Ruta
		{
			get
			{
				return this._Asignacion_Ruta;
			}
			set
			{
				this._Asignacion_Ruta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Factura", Storage="_Factura", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Pedido", Storage="_Pedido", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asignacion_Ruta(Asignacion_Ruta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Asignacion_Ruta(Asignacion_Ruta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auditoria")]
	public partial class Auditoria
	{
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _usuario;
		
		private string _tipo_trans;
		
		public Auditoria()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(35)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_trans", DbType="VarChar(50)")]
		public string tipo_trans
		{
			get
			{
				return this._tipo_trans;
			}
			set
			{
				if ((this._tipo_trans != value))
				{
					this._tipo_trans = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Factura")]
	public partial class Detalle_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detalleFactura;
		
		private int _id_factura;
		
		private int _id_producto;
		
		private int _cantidad;
		
		private decimal _precio;
		
		private decimal _subtotal;
		
		private EntityRef<Factura> _Factura;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalleFacturaChanging(int value);
    partial void Onid_detalleFacturaChanged();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OnsubtotalChanging(decimal value);
    partial void OnsubtotalChanged();
    #endregion
		
		public Detalle_Factura()
		{
			this._Factura = default(EntityRef<Factura>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalleFactura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detalleFactura
		{
			get
			{
				return this._id_detalleFactura;
			}
			set
			{
				if ((this._id_detalleFactura != value))
				{
					this.Onid_detalleFacturaChanging(value);
					this.SendPropertyChanging();
					this._id_detalleFactura = value;
					this.SendPropertyChanged("id_detalleFactura");
					this.Onid_detalleFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", DbType="Int NOT NULL")]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					if (this._Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(6,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Detalle_Factura", Storage="_Factura", ThisKey="id_factura", OtherKey="id_factura", IsForeignKey=true)]
		public Factura Factura
		{
			get
			{
				return this._Factura.Entity;
			}
			set
			{
				Factura previousValue = this._Factura.Entity;
				if (((previousValue != value) 
							|| (this._Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura.Entity = null;
						previousValue.Detalle_Factura.Remove(this);
					}
					this._Factura.Entity = value;
					if ((value != null))
					{
						value.Detalle_Factura.Add(this);
						this._id_factura = value.id_factura;
					}
					else
					{
						this._id_factura = default(int);
					}
					this.SendPropertyChanged("Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Factura", Storage="_Producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_Factura.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_Factura.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Pedido")]
	public partial class Detalle_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detalle;
		
		private int _id_pedido;
		
		private int _id_producto;
		
		private int _cantidad;
		
		private decimal _precio_producto;
		
		private decimal _subtotal;
		
		private EntityRef<Pedido> _Pedido;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalleChanging(int value);
    partial void Onid_detalleChanged();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onprecio_productoChanging(decimal value);
    partial void Onprecio_productoChanged();
    partial void OnsubtotalChanging(decimal value);
    partial void OnsubtotalChanged();
    #endregion
		
		public Detalle_Pedido()
		{
			this._Pedido = default(EntityRef<Pedido>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detalle
		{
			get
			{
				return this._id_detalle;
			}
			set
			{
				if ((this._id_detalle != value))
				{
					this.Onid_detalleChanging(value);
					this.SendPropertyChanging();
					this._id_detalle = value;
					this.SendPropertyChanged("id_detalle");
					this.Onid_detalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", DbType="Int NOT NULL")]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_producto", DbType="Money NOT NULL")]
		public decimal precio_producto
		{
			get
			{
				return this._precio_producto;
			}
			set
			{
				if ((this._precio_producto != value))
				{
					this.Onprecio_productoChanging(value);
					this.SendPropertyChanging();
					this._precio_producto = value;
					this.SendPropertyChanged("precio_producto");
					this.Onprecio_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Money NOT NULL")]
		public decimal subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Detalle_Pedido", Storage="_Pedido", ThisKey="id_pedido", OtherKey="id_pedido", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Detalle_Pedido.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Detalle_Pedido.Add(this);
						this._id_pedido = value.id_pedido;
					}
					else
					{
						this._id_pedido = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Pedido", Storage="_Producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_Pedido.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_Pedido.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Devolucion")]
	public partial class Devolucion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_devolucion;
		
		private int _id_producto;
		
		private int _id_asignacion;
		
		private int _id_punto;
		
		private int _cantidad;
		
		private decimal _motivo;
		
		private string _descripcion;
		
		private System.DateTime _fecha_devolucion;
		
		private EntityRef<Asignacion_Ruta> _Asignacion_Ruta;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Punto> _Punto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_devolucionChanging(int value);
    partial void Onid_devolucionChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void Onid_asignacionChanging(int value);
    partial void Onid_asignacionChanged();
    partial void Onid_puntoChanging(int value);
    partial void Onid_puntoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnmotivoChanging(decimal value);
    partial void OnmotivoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_devolucionChanging(System.DateTime value);
    partial void Onfecha_devolucionChanged();
    #endregion
		
		public Devolucion()
		{
			this._Asignacion_Ruta = default(EntityRef<Asignacion_Ruta>);
			this._Producto = default(EntityRef<Producto>);
			this._Punto = default(EntityRef<Punto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_devolucion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_devolucion
		{
			get
			{
				return this._id_devolucion;
			}
			set
			{
				if ((this._id_devolucion != value))
				{
					this.Onid_devolucionChanging(value);
					this.SendPropertyChanging();
					this._id_devolucion = value;
					this.SendPropertyChanged("id_devolucion");
					this.Onid_devolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_asignacion", DbType="Int NOT NULL")]
		public int id_asignacion
		{
			get
			{
				return this._id_asignacion;
			}
			set
			{
				if ((this._id_asignacion != value))
				{
					if (this._Asignacion_Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_asignacionChanging(value);
					this.SendPropertyChanging();
					this._id_asignacion = value;
					this.SendPropertyChanged("id_asignacion");
					this.Onid_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_punto", DbType="Int NOT NULL")]
		public int id_punto
		{
			get
			{
				return this._id_punto;
			}
			set
			{
				if ((this._id_punto != value))
				{
					if (this._Punto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_puntoChanging(value);
					this.SendPropertyChanging();
					this._id_punto = value;
					this.SendPropertyChanged("id_punto");
					this.Onid_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="Decimal(1,0) NOT NULL")]
		public decimal motivo
		{
			get
			{
				return this._motivo;
			}
			set
			{
				if ((this._motivo != value))
				{
					this.OnmotivoChanging(value);
					this.SendPropertyChanging();
					this._motivo = value;
					this.SendPropertyChanged("motivo");
					this.OnmotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_devolucion", DbType="Date NOT NULL")]
		public System.DateTime fecha_devolucion
		{
			get
			{
				return this._fecha_devolucion;
			}
			set
			{
				if ((this._fecha_devolucion != value))
				{
					this.Onfecha_devolucionChanging(value);
					this.SendPropertyChanging();
					this._fecha_devolucion = value;
					this.SendPropertyChanged("fecha_devolucion");
					this.Onfecha_devolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asignacion_Ruta_Devolucion", Storage="_Asignacion_Ruta", ThisKey="id_asignacion", OtherKey="id_asignacion", IsForeignKey=true)]
		public Asignacion_Ruta Asignacion_Ruta
		{
			get
			{
				return this._Asignacion_Ruta.Entity;
			}
			set
			{
				Asignacion_Ruta previousValue = this._Asignacion_Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Asignacion_Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asignacion_Ruta.Entity = null;
						previousValue.Devolucion.Remove(this);
					}
					this._Asignacion_Ruta.Entity = value;
					if ((value != null))
					{
						value.Devolucion.Add(this);
						this._id_asignacion = value.id_asignacion;
					}
					else
					{
						this._id_asignacion = default(int);
					}
					this.SendPropertyChanged("Asignacion_Ruta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Devolucion", Storage="_Producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Devolucion.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Devolucion.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Punto_Devolucion", Storage="_Punto", ThisKey="id_punto", OtherKey="id_punto", IsForeignKey=true)]
		public Punto Punto
		{
			get
			{
				return this._Punto.Entity;
			}
			set
			{
				Punto previousValue = this._Punto.Entity;
				if (((previousValue != value) 
							|| (this._Punto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Punto.Entity = null;
						previousValue.Devolucion.Remove(this);
					}
					this._Punto.Entity = value;
					if ((value != null))
					{
						value.Devolucion.Add(this);
						this._id_punto = value.id_punto;
					}
					else
					{
						this._id_punto = default(int);
					}
					this.SendPropertyChanged("Punto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entrega")]
	public partial class Entrega : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_entrega;
		
		private int _id_pedido;
		
		private int _id_asignacion;
		
		private string _estado_entrega;
		
		private EntityRef<Asignacion_Ruta> _Asignacion_Ruta;
		
		private EntityRef<Pedido> _Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_entregaChanging(int value);
    partial void Onid_entregaChanged();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void Onid_asignacionChanging(int value);
    partial void Onid_asignacionChanged();
    partial void Onestado_entregaChanging(string value);
    partial void Onestado_entregaChanged();
    #endregion
		
		public Entrega()
		{
			this._Asignacion_Ruta = default(EntityRef<Asignacion_Ruta>);
			this._Pedido = default(EntityRef<Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entrega", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_entrega
		{
			get
			{
				return this._id_entrega;
			}
			set
			{
				if ((this._id_entrega != value))
				{
					this.Onid_entregaChanging(value);
					this.SendPropertyChanging();
					this._id_entrega = value;
					this.SendPropertyChanged("id_entrega");
					this.Onid_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", DbType="Int NOT NULL")]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_asignacion", DbType="Int NOT NULL")]
		public int id_asignacion
		{
			get
			{
				return this._id_asignacion;
			}
			set
			{
				if ((this._id_asignacion != value))
				{
					if (this._Asignacion_Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_asignacionChanging(value);
					this.SendPropertyChanging();
					this._id_asignacion = value;
					this.SendPropertyChanged("id_asignacion");
					this.Onid_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_entrega", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string estado_entrega
		{
			get
			{
				return this._estado_entrega;
			}
			set
			{
				if ((this._estado_entrega != value))
				{
					this.Onestado_entregaChanging(value);
					this.SendPropertyChanging();
					this._estado_entrega = value;
					this.SendPropertyChanged("estado_entrega");
					this.Onestado_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asignacion_Ruta_Entrega", Storage="_Asignacion_Ruta", ThisKey="id_asignacion", OtherKey="id_asignacion", IsForeignKey=true)]
		public Asignacion_Ruta Asignacion_Ruta
		{
			get
			{
				return this._Asignacion_Ruta.Entity;
			}
			set
			{
				Asignacion_Ruta previousValue = this._Asignacion_Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Asignacion_Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asignacion_Ruta.Entity = null;
						previousValue.Entrega.Remove(this);
					}
					this._Asignacion_Ruta.Entity = value;
					if ((value != null))
					{
						value.Entrega.Add(this);
						this._id_asignacion = value.id_asignacion;
					}
					else
					{
						this._id_asignacion = default(int);
					}
					this.SendPropertyChanged("Asignacion_Ruta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Entrega", Storage="_Pedido", ThisKey="id_pedido", OtherKey="id_pedido", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Entrega.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Entrega.Add(this);
						this._id_pedido = value.id_pedido;
					}
					else
					{
						this._id_pedido = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura")]
	public partial class Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_factura;
		
		private int _id_usuario;
		
		private int _id_punto;
		
		private string _nit;
		
		private string _nombre_propietario;
		
		private System.DateTime _fecha;
		
		private decimal _total;
		
		private EntitySet<Detalle_Factura> _Detalle_Factura;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Punto> _Punto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_puntoChanging(int value);
    partial void Onid_puntoChanged();
    partial void OnnitChanging(string value);
    partial void OnnitChanged();
    partial void Onnombre_propietarioChanging(string value);
    partial void Onnombre_propietarioChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OntotalChanging(decimal value);
    partial void OntotalChanged();
    #endregion
		
		public Factura()
		{
			this._Detalle_Factura = new EntitySet<Detalle_Factura>(new Action<Detalle_Factura>(this.attach_Detalle_Factura), new Action<Detalle_Factura>(this.detach_Detalle_Factura));
			this._Usuario = default(EntityRef<Usuario>);
			this._Punto = default(EntityRef<Punto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_punto", DbType="Int NOT NULL")]
		public int id_punto
		{
			get
			{
				return this._id_punto;
			}
			set
			{
				if ((this._id_punto != value))
				{
					if (this._Punto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_puntoChanging(value);
					this.SendPropertyChanging();
					this._id_punto = value;
					this.SendPropertyChanged("id_punto");
					this.Onid_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				if ((this._nit != value))
				{
					this.OnnitChanging(value);
					this.SendPropertyChanging();
					this._nit = value;
					this.SendPropertyChanged("nit");
					this.OnnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_propietario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_propietario
		{
			get
			{
				return this._nombre_propietario;
			}
			set
			{
				if ((this._nombre_propietario != value))
				{
					this.Onnombre_propietarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_propietario = value;
					this.SendPropertyChanged("nombre_propietario");
					this.Onnombre_propietarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(10,2) NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Detalle_Factura", Storage="_Detalle_Factura", ThisKey="id_factura", OtherKey="id_factura")]
		public EntitySet<Detalle_Factura> Detalle_Factura
		{
			get
			{
				return this._Detalle_Factura;
			}
			set
			{
				this._Detalle_Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Factura", Storage="_Usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Punto_Factura", Storage="_Punto", ThisKey="id_punto", OtherKey="id_punto", IsForeignKey=true)]
		public Punto Punto
		{
			get
			{
				return this._Punto.Entity;
			}
			set
			{
				Punto previousValue = this._Punto.Entity;
				if (((previousValue != value) 
							|| (this._Punto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Punto.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Punto.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._id_punto = value.id_punto;
					}
					else
					{
						this._id_punto = default(int);
					}
					this.SendPropertyChanged("Punto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Factura(Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Factura = this;
		}
		
		private void detach_Detalle_Factura(Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pedido;
		
		private int _id_usuario;
		
		private int _id_ruta;
		
		private int _id_punto;
		
		private System.DateTime _fecha_pedido;
		
		private decimal _estado_pedido;
		
		private EntitySet<Detalle_Pedido> _Detalle_Pedido;
		
		private EntitySet<Entrega> _Entrega;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Punto> _Punto;
		
		private EntityRef<Ruta> _Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_rutaChanging(int value);
    partial void Onid_rutaChanged();
    partial void Onid_puntoChanging(int value);
    partial void Onid_puntoChanged();
    partial void Onfecha_pedidoChanging(System.DateTime value);
    partial void Onfecha_pedidoChanged();
    partial void Onestado_pedidoChanging(decimal value);
    partial void Onestado_pedidoChanged();
    #endregion
		
		public Pedido()
		{
			this._Detalle_Pedido = new EntitySet<Detalle_Pedido>(new Action<Detalle_Pedido>(this.attach_Detalle_Pedido), new Action<Detalle_Pedido>(this.detach_Detalle_Pedido));
			this._Entrega = new EntitySet<Entrega>(new Action<Entrega>(this.attach_Entrega), new Action<Entrega>(this.detach_Entrega));
			this._Usuario = default(EntityRef<Usuario>);
			this._Punto = default(EntityRef<Punto>);
			this._Ruta = default(EntityRef<Ruta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ruta", DbType="Int NOT NULL")]
		public int id_ruta
		{
			get
			{
				return this._id_ruta;
			}
			set
			{
				if ((this._id_ruta != value))
				{
					if (this._Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rutaChanging(value);
					this.SendPropertyChanging();
					this._id_ruta = value;
					this.SendPropertyChanged("id_ruta");
					this.Onid_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_punto", DbType="Int NOT NULL")]
		public int id_punto
		{
			get
			{
				return this._id_punto;
			}
			set
			{
				if ((this._id_punto != value))
				{
					if (this._Punto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_puntoChanging(value);
					this.SendPropertyChanging();
					this._id_punto = value;
					this.SendPropertyChanged("id_punto");
					this.Onid_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_pedido", DbType="Date NOT NULL")]
		public System.DateTime fecha_pedido
		{
			get
			{
				return this._fecha_pedido;
			}
			set
			{
				if ((this._fecha_pedido != value))
				{
					this.Onfecha_pedidoChanging(value);
					this.SendPropertyChanging();
					this._fecha_pedido = value;
					this.SendPropertyChanged("fecha_pedido");
					this.Onfecha_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_pedido", DbType="Decimal(1,0) NOT NULL")]
		public decimal estado_pedido
		{
			get
			{
				return this._estado_pedido;
			}
			set
			{
				if ((this._estado_pedido != value))
				{
					this.Onestado_pedidoChanging(value);
					this.SendPropertyChanging();
					this._estado_pedido = value;
					this.SendPropertyChanged("estado_pedido");
					this.Onestado_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Detalle_Pedido", Storage="_Detalle_Pedido", ThisKey="id_pedido", OtherKey="id_pedido")]
		public EntitySet<Detalle_Pedido> Detalle_Pedido
		{
			get
			{
				return this._Detalle_Pedido;
			}
			set
			{
				this._Detalle_Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Entrega", Storage="_Entrega", ThisKey="id_pedido", OtherKey="id_pedido")]
		public EntitySet<Entrega> Entrega
		{
			get
			{
				return this._Entrega;
			}
			set
			{
				this._Entrega.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Pedido", Storage="_Usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Punto_Pedido", Storage="_Punto", ThisKey="id_punto", OtherKey="id_punto", IsForeignKey=true)]
		public Punto Punto
		{
			get
			{
				return this._Punto.Entity;
			}
			set
			{
				Punto previousValue = this._Punto.Entity;
				if (((previousValue != value) 
							|| (this._Punto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Punto.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Punto.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._id_punto = value.id_punto;
					}
					else
					{
						this._id_punto = default(int);
					}
					this.SendPropertyChanged("Punto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Pedido", Storage="_Ruta", ThisKey="id_ruta", OtherKey="id_ruta", IsForeignKey=true)]
		public Ruta Ruta
		{
			get
			{
				return this._Ruta.Entity;
			}
			set
			{
				Ruta previousValue = this._Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ruta.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Ruta.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._id_ruta = value.id_ruta;
					}
					else
					{
						this._id_ruta = default(int);
					}
					this.SendPropertyChanged("Ruta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
		
		private void attach_Entrega(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Entrega(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private string _descripcion_producto;
		
		private decimal _precio_producto;
		
		private int _stock;
		
		private decimal _estado_producto;
		
		private EntitySet<Detalle_Factura> _Detalle_Factura;
		
		private EntitySet<Detalle_Pedido> _Detalle_Pedido;
		
		private EntitySet<Devolucion> _Devolucion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void Ondescripcion_productoChanging(string value);
    partial void Ondescripcion_productoChanged();
    partial void Onprecio_productoChanging(decimal value);
    partial void Onprecio_productoChanged();
    partial void OnstockChanging(int value);
    partial void OnstockChanged();
    partial void Onestado_productoChanging(decimal value);
    partial void Onestado_productoChanged();
    #endregion
		
		public Producto()
		{
			this._Detalle_Factura = new EntitySet<Detalle_Factura>(new Action<Detalle_Factura>(this.attach_Detalle_Factura), new Action<Detalle_Factura>(this.detach_Detalle_Factura));
			this._Detalle_Pedido = new EntitySet<Detalle_Pedido>(new Action<Detalle_Pedido>(this.attach_Detalle_Pedido), new Action<Detalle_Pedido>(this.detach_Detalle_Pedido));
			this._Devolucion = new EntitySet<Devolucion>(new Action<Devolucion>(this.attach_Devolucion), new Action<Devolucion>(this.detach_Devolucion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_producto", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string descripcion_producto
		{
			get
			{
				return this._descripcion_producto;
			}
			set
			{
				if ((this._descripcion_producto != value))
				{
					this.Ondescripcion_productoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_producto = value;
					this.SendPropertyChanged("descripcion_producto");
					this.Ondescripcion_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_producto", DbType="Decimal(6,2) NOT NULL")]
		public decimal precio_producto
		{
			get
			{
				return this._precio_producto;
			}
			set
			{
				if ((this._precio_producto != value))
				{
					this.Onprecio_productoChanging(value);
					this.SendPropertyChanging();
					this._precio_producto = value;
					this.SendPropertyChanged("precio_producto");
					this.Onprecio_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int NOT NULL")]
		public int stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this.OnstockChanging(value);
					this.SendPropertyChanging();
					this._stock = value;
					this.SendPropertyChanged("stock");
					this.OnstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_producto", DbType="Decimal(1,0) NOT NULL")]
		public decimal estado_producto
		{
			get
			{
				return this._estado_producto;
			}
			set
			{
				if ((this._estado_producto != value))
				{
					this.Onestado_productoChanging(value);
					this.SendPropertyChanging();
					this._estado_producto = value;
					this.SendPropertyChanged("estado_producto");
					this.Onestado_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Factura", Storage="_Detalle_Factura", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<Detalle_Factura> Detalle_Factura
		{
			get
			{
				return this._Detalle_Factura;
			}
			set
			{
				this._Detalle_Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Pedido", Storage="_Detalle_Pedido", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<Detalle_Pedido> Detalle_Pedido
		{
			get
			{
				return this._Detalle_Pedido;
			}
			set
			{
				this._Detalle_Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Devolucion", Storage="_Devolucion", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<Devolucion> Devolucion
		{
			get
			{
				return this._Devolucion;
			}
			set
			{
				this._Devolucion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Factura(Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_Factura(Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_Pedido(Detalle_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Devolucion(Devolucion entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Devolucion(Devolucion entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Punto")]
	public partial class Punto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_punto;
		
		private int _id_ruta;
		
		private string _departamento_punto;
		
		private string _municipio_punto;
		
		private string _direccion_punto;
		
		private decimal _estado_punto;
		
		private string _detalles_punto;
		
		private string _propietario_punto;
		
		private string _nit_punto;
		
		private string _telefono_punto;
		
		private EntitySet<Devolucion> _Devolucion;
		
		private EntitySet<Factura> _Factura;
		
		private EntitySet<Pedido> _Pedido;
		
		private EntityRef<Ruta> _Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_puntoChanging(int value);
    partial void Onid_puntoChanged();
    partial void Onid_rutaChanging(int value);
    partial void Onid_rutaChanged();
    partial void Ondepartamento_puntoChanging(string value);
    partial void Ondepartamento_puntoChanged();
    partial void Onmunicipio_puntoChanging(string value);
    partial void Onmunicipio_puntoChanged();
    partial void Ondireccion_puntoChanging(string value);
    partial void Ondireccion_puntoChanged();
    partial void Onestado_puntoChanging(decimal value);
    partial void Onestado_puntoChanged();
    partial void Ondetalles_puntoChanging(string value);
    partial void Ondetalles_puntoChanged();
    partial void Onpropietario_puntoChanging(string value);
    partial void Onpropietario_puntoChanged();
    partial void Onnit_puntoChanging(string value);
    partial void Onnit_puntoChanged();
    partial void Ontelefono_puntoChanging(string value);
    partial void Ontelefono_puntoChanged();
    #endregion
		
		public Punto()
		{
			this._Devolucion = new EntitySet<Devolucion>(new Action<Devolucion>(this.attach_Devolucion), new Action<Devolucion>(this.detach_Devolucion));
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			this._Ruta = default(EntityRef<Ruta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_punto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_punto
		{
			get
			{
				return this._id_punto;
			}
			set
			{
				if ((this._id_punto != value))
				{
					this.Onid_puntoChanging(value);
					this.SendPropertyChanging();
					this._id_punto = value;
					this.SendPropertyChanged("id_punto");
					this.Onid_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ruta", DbType="Int NOT NULL")]
		public int id_ruta
		{
			get
			{
				return this._id_ruta;
			}
			set
			{
				if ((this._id_ruta != value))
				{
					if (this._Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rutaChanging(value);
					this.SendPropertyChanging();
					this._id_ruta = value;
					this.SendPropertyChanged("id_ruta");
					this.Onid_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento_punto", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string departamento_punto
		{
			get
			{
				return this._departamento_punto;
			}
			set
			{
				if ((this._departamento_punto != value))
				{
					this.Ondepartamento_puntoChanging(value);
					this.SendPropertyChanging();
					this._departamento_punto = value;
					this.SendPropertyChanged("departamento_punto");
					this.Ondepartamento_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio_punto", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string municipio_punto
		{
			get
			{
				return this._municipio_punto;
			}
			set
			{
				if ((this._municipio_punto != value))
				{
					this.Onmunicipio_puntoChanging(value);
					this.SendPropertyChanging();
					this._municipio_punto = value;
					this.SendPropertyChanged("municipio_punto");
					this.Onmunicipio_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_punto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion_punto
		{
			get
			{
				return this._direccion_punto;
			}
			set
			{
				if ((this._direccion_punto != value))
				{
					this.Ondireccion_puntoChanging(value);
					this.SendPropertyChanging();
					this._direccion_punto = value;
					this.SendPropertyChanged("direccion_punto");
					this.Ondireccion_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_punto", DbType="Decimal(1,0) NOT NULL")]
		public decimal estado_punto
		{
			get
			{
				return this._estado_punto;
			}
			set
			{
				if ((this._estado_punto != value))
				{
					this.Onestado_puntoChanging(value);
					this.SendPropertyChanging();
					this._estado_punto = value;
					this.SendPropertyChanged("estado_punto");
					this.Onestado_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalles_punto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string detalles_punto
		{
			get
			{
				return this._detalles_punto;
			}
			set
			{
				if ((this._detalles_punto != value))
				{
					this.Ondetalles_puntoChanging(value);
					this.SendPropertyChanging();
					this._detalles_punto = value;
					this.SendPropertyChanged("detalles_punto");
					this.Ondetalles_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_propietario_punto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string propietario_punto
		{
			get
			{
				return this._propietario_punto;
			}
			set
			{
				if ((this._propietario_punto != value))
				{
					this.Onpropietario_puntoChanging(value);
					this.SendPropertyChanging();
					this._propietario_punto = value;
					this.SendPropertyChanged("propietario_punto");
					this.Onpropietario_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_punto", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string nit_punto
		{
			get
			{
				return this._nit_punto;
			}
			set
			{
				if ((this._nit_punto != value))
				{
					this.Onnit_puntoChanging(value);
					this.SendPropertyChanging();
					this._nit_punto = value;
					this.SendPropertyChanged("nit_punto");
					this.Onnit_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_punto", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string telefono_punto
		{
			get
			{
				return this._telefono_punto;
			}
			set
			{
				if ((this._telefono_punto != value))
				{
					this.Ontelefono_puntoChanging(value);
					this.SendPropertyChanging();
					this._telefono_punto = value;
					this.SendPropertyChanged("telefono_punto");
					this.Ontelefono_puntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Punto_Devolucion", Storage="_Devolucion", ThisKey="id_punto", OtherKey="id_punto")]
		public EntitySet<Devolucion> Devolucion
		{
			get
			{
				return this._Devolucion;
			}
			set
			{
				this._Devolucion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Punto_Factura", Storage="_Factura", ThisKey="id_punto", OtherKey="id_punto")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Punto_Pedido", Storage="_Pedido", ThisKey="id_punto", OtherKey="id_punto")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Punto", Storage="_Ruta", ThisKey="id_ruta", OtherKey="id_ruta", IsForeignKey=true)]
		public Ruta Ruta
		{
			get
			{
				return this._Ruta.Entity;
			}
			set
			{
				Ruta previousValue = this._Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ruta.Entity = null;
						previousValue.Punto.Remove(this);
					}
					this._Ruta.Entity = value;
					if ((value != null))
					{
						value.Punto.Add(this);
						this._id_ruta = value.id_ruta;
					}
					else
					{
						this._id_ruta = default(int);
					}
					this.SendPropertyChanged("Ruta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Devolucion(Devolucion entity)
		{
			this.SendPropertyChanging();
			entity.Punto = this;
		}
		
		private void detach_Devolucion(Devolucion entity)
		{
			this.SendPropertyChanging();
			entity.Punto = null;
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Punto = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Punto = null;
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Punto = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Punto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ruta")]
	public partial class Ruta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ruta;
		
		private string _descripcion_ruta;
		
		private decimal _estado_ruta;
		
		private EntitySet<Asignacion_Ruta> _Asignacion_Ruta;
		
		private EntitySet<Pedido> _Pedido;
		
		private EntitySet<Punto> _Punto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rutaChanging(int value);
    partial void Onid_rutaChanged();
    partial void Ondescripcion_rutaChanging(string value);
    partial void Ondescripcion_rutaChanged();
    partial void Onestado_rutaChanging(decimal value);
    partial void Onestado_rutaChanged();
    #endregion
		
		public Ruta()
		{
			this._Asignacion_Ruta = new EntitySet<Asignacion_Ruta>(new Action<Asignacion_Ruta>(this.attach_Asignacion_Ruta), new Action<Asignacion_Ruta>(this.detach_Asignacion_Ruta));
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			this._Punto = new EntitySet<Punto>(new Action<Punto>(this.attach_Punto), new Action<Punto>(this.detach_Punto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ruta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ruta
		{
			get
			{
				return this._id_ruta;
			}
			set
			{
				if ((this._id_ruta != value))
				{
					this.Onid_rutaChanging(value);
					this.SendPropertyChanging();
					this._id_ruta = value;
					this.SendPropertyChanged("id_ruta");
					this.Onid_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_ruta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion_ruta
		{
			get
			{
				return this._descripcion_ruta;
			}
			set
			{
				if ((this._descripcion_ruta != value))
				{
					this.Ondescripcion_rutaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_ruta = value;
					this.SendPropertyChanged("descripcion_ruta");
					this.Ondescripcion_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_ruta", DbType="Decimal(1,0) NOT NULL")]
		public decimal estado_ruta
		{
			get
			{
				return this._estado_ruta;
			}
			set
			{
				if ((this._estado_ruta != value))
				{
					this.Onestado_rutaChanging(value);
					this.SendPropertyChanging();
					this._estado_ruta = value;
					this.SendPropertyChanged("estado_ruta");
					this.Onestado_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Asignacion_Ruta", Storage="_Asignacion_Ruta", ThisKey="id_ruta", OtherKey="id_ruta")]
		public EntitySet<Asignacion_Ruta> Asignacion_Ruta
		{
			get
			{
				return this._Asignacion_Ruta;
			}
			set
			{
				this._Asignacion_Ruta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Pedido", Storage="_Pedido", ThisKey="id_ruta", OtherKey="id_ruta")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Punto", Storage="_Punto", ThisKey="id_ruta", OtherKey="id_ruta")]
		public EntitySet<Punto> Punto
		{
			get
			{
				return this._Punto;
			}
			set
			{
				this._Punto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asignacion_Ruta(Asignacion_Ruta entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = this;
		}
		
		private void detach_Asignacion_Ruta(Asignacion_Ruta entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = null;
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = null;
		}
		
		private void attach_Punto(Punto entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = this;
		}
		
		private void detach_Punto(Punto entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = null;
		}
	}
}
#pragma warning restore 1591
